### ISSUE TITLE
Subsequent password checks are impossible to complete at the same time

### ISSUE THREAD

**Issue by tomzorz** [LanceMcCarthy/dotnet-password-purgatory#7]
The 

> Password must contain only unique characters.

[rule](https://github.com/LanceMcCarthy/dotnet-password-purgatory/blob/main/src/PasswordPurgatory/PasswordPurgatory.Web/Models/Check.cs#L197) conflicts with the next [rule](https://github.com/LanceMcCarthy/dotnet-password-purgatory/blob/main/src/PasswordPurgatory/PasswordPurgatory.Web/Models/Check.cs#L203) in the line

> Password must contain 'Password must contain' (case sensitive)

as just in that line the S character exists 3 times (`paSSword muSt contain`), so even with case sensitivity both rules can't be satisfied at the same time.

**Comment by LanceMcCarthy** [comment]
Ooo, good point. So if I want them to try and reach the last one (which is truly impossible), I can just remove the unique characters one (because the "password must contain 'password must contain is so much funnier)

**Comment by LanceMcCarthy** [comment]
Merged, when this Action is completed, the app will be live on Azure https://github.com/LanceMcCarthy/dotnet-password-purgatory/actions

**Comment by LanceMcCarthy** [comment]
I forgot to mention, block comments don't work in lists. I changed it to line-comments and that's what is in the final release:

https://github.com/LanceMcCarthy/dotnet-password-purgatory/blob/f0f5feaf17fe4d6ec85d9df254b853a07b19075c/src/PasswordPurgatory/PasswordPurgatory.Web/Models/Check.cs#L197-L202
